### ISSUE TITLE
validation report integration

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#163] opened 2023-11-07 19:10 UTC
Validation report information: 
- documentation:
- docker container: 
- @aozalevsky to update with requirements

**Comment by svoinea** [comment] 2023-11-21 20:48
File System on PDB AWS DEV:
```
df -h
Filesystem                Size  Used Avail Use% Mounted on
devtmpfs                  4.0M     0  4.0M   0% /dev
tmpfs                     7.8G   28K  7.8G   1% /dev/shm
tmpfs                     3.1G  728K  3.1G   1% /run
/dev/nvme0n1p5             19G  5.3G   14G  29% /
tmpfs                     7.8G   12K  7.8G   1% /tmp
/dev/nvme0n1p2            966M  293M  608M  33% /boot
/dev/nvme0n1p3            100M   12M   89M  12% /boot/efi
/dev/mapper/data-scratch   20G  176M   20G   1% /scratch
/dev/mapper/data-www       50G   13G   38G  26% /var/www
/dev/mapper/data-home      10G  3.1G  7.0G  31% /home
/dev/mapper/data-pgsql     30G  5.0G   25G  17% /var/lib/pgsql
tmpfs                     1.6G  4.0K  1.6G   1% /run/user/2010
```
File System on PDB AWS Production:
```
df -h
Filesystem                Size  Used Avail Use% Mounted on
devtmpfs                  4.0M     0  4.0M   0% /dev
tmpfs                     3.9G   28K  3.9G   1% /dev/shm
tmpfs                     1.6G  736K  1.6G   1% /run
/dev/nvme1n1p5             19G  4.0G   15G  22% /
tmpfs                     3.9G  8.0K  3.9G   1% /tmp
/dev/nvme1n1p2            966M  293M  607M  33% /boot
/dev/nvme1n1p3            100M   12M   89M  12% /boot/efi
/dev/mapper/data-pgsql     30G  2.4G   28G   8% /var/lib/pgsql
/dev/mapper/data-home      10G  2.8G  7.2G  29% /home
/dev/mapper/data-scratch   20G  176M   20G   1% /scratch
/dev/mapper/data-www       50G   13G   38G  26% /var/www
tmpfs                     783M  4.0K  783M   1% /run/user/2010
```

**Comment by aozalevsky** [comment] 2023-11-21 22:25
My current estimates:

1) docker container - 13.0G
2) EMDB+SASBDB database cache - 1.4G
3) current calculation cache (molprobity, excluded volume) 0.1GB
4) current outputs (htmls + pdfs)  0.1GB
5) current PDBDEV mmCIFs 0.4GB

Total: 15GB

**Comment by hongsudt** [comment] 2023-11-22 00:33
These files have to be in the same folder, right? e.g. we can't put the
cache folders in a different location from the docker container?

**Comment by aozalevsky** [comment] 2023-11-28 19:00
After the discussion with Brinda, and to simplify the deployment in the scope of RCSB PDB infrastructure i opted to `singularity` because unlike `docker` or `podman` it allows to have an image as one compressed binary file. 

If you have an access to the `docker-pdbdev-validation` instance in order to run the pipeline you have to:

1. `cd /mnt/vdb1/dev`
2. copy the input cif files to `input` folder or just get a path to the other directory
3. run the pipeline like this:
```
singularity exec --bind IHMValidation_2.0_20231128/:/opt/IHMValidation,output:/output,cache:/cache,input:/input ihmv.cif /opt/IHMValidation/ihm_validation/ihm_validator.py -f /input/PDBDEV_00000004.cif --force --output-root /output --cache-root /cache
```

Here is a detailed explanation of the options:
`singularity exec` - calls singularity container to execute just one command
`--bind IHMValidation_2.0_20231128/:/opt/IHMValidation` - mounts the current version of the software (https://github.com/aozalevsky/IHMValidation_2.0) inside the container
`,output:/output,cache:/cache,input:/input` - mounts other input and output directories
`hmv.cif` - name of the container
`/opt/IHMValidation/ihm_validation/ihm_validator.py` - path to the main script inside the container
`-f /input/PDBDEV_00000004.cif` - path to the input file relative to the container. notice that we mounted `input` directory to the `/input` inside the container
`--force` -- overwrite output if it exists
`--output-root /output` - set path to the output
` --cache-root /cache` - set path to the temp directory with intermediate calc results.

**Comment by aozalevsky** [comment] 2023-12-05 19:39
@svoinea just in case:

`/mnt/vdb1` - a 100G volume that we can use for any purposes
`/mnt/vdb1/dev_pdbihm` - copied everything under `/mnt/vdb1/dev` and changed the owner to `pdbihm`

i verified that it works under `pdbihm` user like this:
```
sudo -u pdbihm singularity exec --bind IHMValidation_2.0_20231130/:/opt/IHMValidation,output:/ihmv/output,cache:/ihmv/cache,input:/ihmv/input ihmv_20231130.sif /opt/IHMValidation/ihm_validation/ihm_validator.py -f /ihmv/input/PDBDEV_00000001.cif --force --output-root /ihmv/output --cache-root /ihmv/cache
```

**Comment by svoinea** [comment] 2023-12-12 17:52
I tested with the `pdbihm` user and it works as expected.

**Comment by svoinea** [comment] 2023-12-13 19:20
@aozalevsky A case that does not work:
```
cd /mnt/vdb1/dev_pdbihm
singularity exec --bind IHMValidation_2.0_20231130/:/opt/IHMValidation,output:/ihmv/output,cache:/ihmv/cache,input:/ihmv/input ihmv_20231130.sif /opt/IHMValidation/ihm_validation/ihm_validator.py -f /ihmv/input/PDBDEV_00000185.cif --force --output-root /ihmv/output --cache-root /ihmv/cache
```
The test was run with the `pdbihm` user.
It did not finished after `2 hours` and I have killed the process.
`PDBDEV_00000185.cif` is a System Generated mmCIF File.
Based on what I saw in `top` command, it seems to be in an `ever` loop, probably due to the content of the `PDBDEV_00000185.cif` file.

The output generated so far:
```
INFO:root:Current operational mode is: PRODUCTION
INFO:root:Clean up and create output directories
INFO:root:Directory /ihmv/output/PDBDEV_00000185 created 
INFO:root:Directory /ihmv/output/PDBDEV_00000185/PDBDEV_00000185_html created 
INFO:root:Directory /ihmv/output/PDBDEV_00000185/PDBDEV_00000185_html/images created 
INFO:root:Directory /ihmv/output/PDBDEV_00000185/PDBDEV_00000185_html/csv created 
INFO:root:Directory /ihmv/output/PDBDEV_00000185/PDBDEV_00000185_html/pdf created 
INFO:root:Entry composition
INFO:root:Model quality
INFO:root:Molprobity analysis is being calculated...
Starting molprobity.clashscore
on Wed Dec 13 16:29:30 2023 by pdbihm
===============================================================================

Processing files:
-------------------------------------------------------------------------------

  Found model, /ihmv/cache/temp.cif

Processing PHIL parameters:
-------------------------------------------------------------------------------

  No PHIL parameters found

Final processed PHIL parameters:
-------------------------------------------------------------------------------
  data_manager {
    model {
      file = "/ihmv/cache/temp.cif"
    }
    default_model = "/ihmv/cache/temp.cif"
  }


Starting job
===============================================================================

===============================================================================
Job complete
usr+sys time: 272.60 seconds
wall clock time: 14 minutes 24.93 seconds (864.93 seconds total)
Starting molprobity.ramalyze
on Wed Dec 13 16:43:56 2023 by pdbihm
===============================================================================

Processing files:
-------------------------------------------------------------------------------

  Found model, /ihmv/cache/temp.cif

Processing PHIL parameters:
-------------------------------------------------------------------------------

  No PHIL parameters found

Final processed PHIL parameters:
-------------------------------------------------------------------------------
  data_manager {
    model {
      file = "/ihmv/cache/temp.cif"
    }
    default_model = "/ihmv/cache/temp.cif"
  }


Starting job
===============================================================================

===============================================================================
Job complete
usr+sys time: 218.45 seconds
wall clock time: 3 minutes 38.58 seconds (218.58 seconds total)
Starting molprobity.rotalyze
on Wed Dec 13 16:47:36 2023 by pdbihm
===============================================================================

Processing files:
-------------------------------------------------------------------------------

  Found model, /ihmv/cache/temp.cif

Processing PHIL parameters:
-------------------------------------------------------------------------------

  No PHIL parameters found

Final processed PHIL parameters:
-------------------------------------------------------------------------------
  data_manager {
    model {
      file = "/ihmv/cache/temp.cif"
    }
    default_model = "/ihmv/cache/temp.cif"
  }


Starting job
===============================================================================

===============================================================================
Job complete
usr+sys time: 101.05 seconds
wall clock time: 101.50 seconds
client_loop: send disconnect: Broken pipe
```

**Comment by svoinea** [comment] 2023-12-13 19:32
@aozalevsky Ignore the last line from the output `client_loop: send disconnect: Broken pipe` as it comes from the `ssh` which disconnected due to the inactivity.

The original file was `input.cif` provided by @brindakv. It is used by me in testing on `dev` and it passes all the steps and generated the System Generated mmCIF File.

**Comment by aozalevsky** [comment] 2023-12-13 19:35
got it. testing right now. I'll let you know asap.

**Comment by aozalevsky** [comment] 2023-12-13 20:49
@svoinea ok, i found the issue. 

It hangs during the PDF rendering because the report is very long. The report is long because there are more than 3k outliers (which would result in around 1.5k pages PDF). We've never experienced anything like this. I have to think about how to deal with this. 

@brindakv I also noticed that Serban's file is different from what i can see in mmcif directory:

Here is a header of the Serban's file:

```
data_PDBDEV_00000185

#
_entry.id  PDBDEV_00000185
#
loop_
_atom_type.symbol
C
H
N
O
S
#
loop_
_audit_author.name
_audit_author.pdbx_ordinal
"Hamilton, G."  1
" Saikia, N."   2
" Basak, S."    3
" Welcome, F. S."       4
" Wu, F."       5
" Kubiak, J."   6
" Zhang, C."    7
" Hao, Y."      8
" Seidel, C. A. M."     9
" Ding, F."     10
" Sanabria, H." 11
" Bowen, M. E." 12
"Dimura, M."    13
"Peulen, T.-O." 14
"Sanabria, H."  15
"Rodnin, D."    16
"Hemmen, K."    17
"Hanke, C.A."   18
"Seidel, C.A.M."        19
"Gohlke, H."    20
```

And here is the one in the `/dev/vdb1/mmcif`:
```
data_PDBDEV_00000185

#
_entry.id  PDBDEV_00000185
#
loop_
_atom_type.symbol
C
H
N
O
S
#
loop_
_audit_author.name
_audit_author.pdbx_ordinal
"Stahl, K."     1
"Graziadei, A." 2
"Dau, T."       3
"Brock, O."     4
"Rappsilber, J."        5
#
```

Those two are different entries, but both have the same ID, is that right? (i guess that might be related to different ids on the dev and production?)

Also, Serban's file has 200 models, which automatically bloats the report because of the per-model plots/data. Let's discuss it during tomorrow's PDB-DEV meeting.

**Comment by aozalevsky** [comment] 2023-12-13 20:49
@svoinea can you test it with a different (smaller) mmcif file for a while?

**Comment by aozalevsky** [comment] 2023-12-13 20:50
@brindakv on a side note:

leading spaces in Serban's file look strange, shouldn't they be automatically stripped?

**Comment by svoinea** [comment] 2023-12-13 21:05
@aozalevsky With smaller files like those that were already present in the `input` directory (`PDBDEV_00000001.cif`, `PDBDEV_00000004.cif`, 'PDBDEV_00000014.cif`), it worked w/o any problems.

Is it in general a limit of the file size? The `PDBDEV_00000185.cif` file has for example `672M`.

**Comment by brindakv** [comment] 2023-12-13 21:36
@aozalevsky `PDBDEV_00000185` on `dev` is different from that on `production`. @svoinea is using the one from `dev`, which may not be correct.

**Comment by brindakv** [comment] 2023-12-13 21:37
@svoinea Please use entries with status `REL` on production for your testing.

**Comment by svoinea** [comment] 2023-12-15 02:13
The PDB production has `69` entries in the `REL` status.
The size of the System Generated mmCIF files is in the range `[158K, 64M]`.
I have tried the one with the maximum size, `PDBDEV_00000164.cif`, corresponding to the entry with `RID = 2-FCA4`.
The `singularity` behaviour is similar to the one I have tested from on dev: it did not finished after `5 hours`.

The `singularity` processing time is an issue.
If it is high, I think we need a separate service which will detect the new System Generated mmCIF files.
Including the `singularity` into the backend, will block the backend to serve other requests during the `singularity` processing time.

**Comment by aozalevsky** [comment] 2023-12-15 02:58
got it, i'll check it out.

**Comment by aozalevsky** [comment] 2023-12-26 16:49
@svoinea there were two issues:
1. memory leak due to the call to browser for rendering pdf. after completion, the browser-daemon instance would reside in memory. i fixed this by adding `--pid` option to the `singularity` call which forces all processes to be in the container's namespace and killed after the exit. 

2. memory leak caused by incompatible options in molprobity (the 3d party software that we are using). i fixed the call. 

I've updated the code and the image accordingly. Here is the updated command:

```
singularity exec --pid --bind IHMValidation_2.0_20231222/:/opt/IHMValidation,input:/ihmv/input,cache:/ihmv/cache,output:/ihmv/output ihmv_20231222.sif /opt/IHMValidation/ihm_validation/ihm_validator.py -f /ihmv/input/PDBDEV_00000164.cif --force --output-root /ihmv/output --cache-root /ihmv/cache
```

It took ~23m to complete:
```
real    22m8.234s
user    17m14.731s
sys     4m8.642s
```

so the 30m time threshold seems reasonable. Can you test the update when you have a minute?

**Comment by brindakv** [comment] 2024-01-05 20:23
@svoinea to make the time threshold a config parameter.

**Comment by svoinea** [comment] 2024-01-06 21:54
Added the `timeout` config parameter.
Updated the Python call to the `singularity` tool based on the above command.

**Comment by brindakv** [comment] 2024-01-31 01:55
@aozalevsky the validation reports generated using the method provided here are very different from the validation reports currently released on PDB-Dev.

**Comment by brindakv** [comment] 2024-02-06 19:10
@aozalevsky to provide deployment script for validation package.

**Comment by aozalevsky** [comment] 2024-02-20 18:43
@svoinea 

I've updated the code for the validation report, can you please test if it works? Everything is in the same place as before, but I updated the revision of IHMValidation_2.0 code to 20240220 hence `IHMValidation_2.0_20240220`.

as `pdbihm` user in `/mnt/vdb1/dev_pdbihm` on the dev instance. 
```
singularity exec --pid --bind IHMValidation_2.0_20240220/:/opt/IHMValidation,input:/ihmv/input,cache:/ihmv/cache,output:/ihmv/output ihmv_20231222.sif /opt/IHMValidation/ihm_validation/ihm_validator.py -f /ihmv/input/PDBDEV_00000191.cif --force --output-root /ihmv/output --cache-root /ihmv/cache
```

**Comment by brindakv** [comment] 2024-02-20 18:44
The above updates the generation of pdf reports but html reports are yet to be updated in the next iteration.

**Comment by svoinea** [comment] 2024-02-21 02:34
@aozalevsky I see some differences between the `singularity` parameters on `dev` and on `production` (from the https://github.com/salilab/IHMValidation/blob/dev_2.0/docker/deploy.sh file):
```
on dev: IHMValidation_2.0_20240220		on production: IHMValidation
on dev: --cache-root				on production: --cache
```
Are they OK?

**Comment by aozalevsky** [comment] 2024-02-21 03:05
@svoinea oh! thanks for pointing this out. that was typo and the correct option is `--cache-root`. Actually, now I'm surprised that it didn't fail during the test. Apparently, newer versions of `argparse` can guess similar options. I've prepared a toy example that shows that it interprets `--cache` as `--cache-root`. 

Here is the code:

```
import argparse
a = argparse.ArgumentParser()
a.add_argument('--cache-root')

args = a.parse_args()
print(args)
```

And here is the output with two different invocations:
```
silwer@flute /tmp $ python3 ag.py --cache A
Namespace(cache_root='A')
silwer@flute /tmp $ python3 ag.py --cache-root A
Namespace(cache_root='A')
```

So, again, the correct option is `--cache-root` and I'll update the call in the deployment script later today.

**Comment by brindakv** [comment] 2024-02-21 18:04
@svoinea https://github.com/salilab/IHMValidation/blob/dev_2.0/docker/deploy.sh is now fixed in the deployment script. 

Do you want to reset the production instance to test the deployment script again?

**Comment by aozalevsky** [comment] 2024-02-21 19:06
@svoinea we've updated a couple more things related to the HTML version of the report. what would be the best way to populate it to dev? 

I've pulled it into another date-tagged directory: `/mnt/vdb1/dev_pdbihm/IHMValidation_2.0_20240221/` 

is it ok?

**Comment by svoinea** [comment] 2024-02-22 00:08
@aozalevsky My opinion is to define a symbolic link `IHMValidation` which points for example to `IHMValidation_2.0_20240221`.
Each time you come up with a new version, execute something like:
```
cd /mnt/vdb1/dev_pdbihm
unlink IHMValidation
ln -s <IHMValidation new version> IHMValidation
```
For now, I have just created the symbolic link `ln -s IHMValidation_2.0_20240221 IHMValidation`.
If you agree, I can make the change in my code to use `IHMValidation` instead of the current `IHMValidation_2.0_20240221`, and to avoid in this way to update my code each time a new version is used.

**Comment by aozalevsky** [comment] 2024-02-22 00:15
@svoinea sounds good to me!

**Comment by brindakv** [comment] 2024-02-22 00:27
@svoinea that's a good idea. Please change your code to use `IHMValidation` instead of `IHMValidation_2.0_20240221` if the symbolic link is in place.

**Comment by svoinea** [comment] 2024-02-22 00:40
@brindakv I have already done the update and re-deployed.

**Comment by brindakv** [comment] 2024-02-23 03:58
Thanks @svoinea. Testing is in progress.

**Comment by svoinea** [comment] 2024-02-26 20:51
@aozalevsky `singularity` on production (`128.6.158.145`) seems not working.
I did the installation on `FEB, 21` as mentioned in your script:
```
git clone --branch dev_2.0 https://github.com/salilab/IHMValidation.git
```

The commands I was running as `pdbihm` user:
```
time singularity exec --pid --bind IHMValidation/:/opt/IHMValidation,input:/ihmv/input,cache:/ihmv/cache,output:/ihmv/output ihmv_20231222.sif /opt/IHMValidation/ihm_validation/ihm_validator.py -f /ihmv/input/PDBDEV_00000191.cif --force --output-root /ihmv/output --cache-root /ihmv/cache
```
After more than 1 hour, `a memory usage limit spike` was reported, after which I have killed the process.
The last printed lines were:
```
Starting job
===============================================================================

===============================================================================
Job complete
usr+sys time: 100.99 seconds
wall clock time: 101.03 seconds
```
I have cleared the `output` and `cache` directories and the `PDBDEV_00000191.cif` is in the `input` directory.

**Comment by aozalevsky** [comment] 2024-02-26 20:56
@svoinea got it. i'll look into it.

**Comment by aozalevsky** [comment] 2024-02-27 00:47
@svoinea i found a regression in one of the latest bulk updates. I've pushed the fix and pulled the update on both dev and production instance. I've tested the fix on production too - it worked ok. I also cleared the cache and output after my test, so when you test it, it'll be like from scratch.

**Comment by brindakv** [comment] 2024-02-27 00:48
Thanks @aozalevsky. @svoinea Please test again.

**Comment by svoinea** [comment] 2024-02-27 03:07
@aozalevsky It worked. Thanks.

**Comment by brindakv** [comment] 2024-02-27 19:08
@svoinea to test the validation report generation on catalog `50` using the workflow production instance. 

@brindakv will check the output files for consistency.

**Comment by brindakv** [comment] 2024-02-27 22:37
Thanks @aozalevsky. 

@svoinea The previous version of `py-rcsb_db` was 0.85. This is 0.86.

**Comment by aozalevsky** [comment] 2024-03-01 02:05
@hongsudt  @svoinea 

I added documentation on how to generate `.sif` images. 

https://github.com/salilab/IHMValidation/tree/dev_2.0/docker 

But there is a catch:

1. One of the dependencies (Molprobity) uses a rolling release model and we can't freeze its version in the deployment script. (See https://github.com/salilab/IHMValidation/issues/72 for details) 
2. Thus, there is a chance that our pipeline won't work with a freshly-compiled image. 
3. So our deployment scheme in the future will look similar to what we've used so far:
a) We generate date-tagged `.sif` image on `dev` instance
b) Test the pipeline on `dev`; tag the `IHMValidation` release
c) Put `.sif` image to storage
d) On `production`: pull pre-compiled `.sif` image from storage; pull tagged `IHMValidation` release from github. 

Does this make sense to you?

**Comment by aozalevsky** [comment] 2024-03-19 21:04
@svoinea here is an update to the singularity call:

```
singularity exec --pid --bind IHMValidation/:/opt/IHMValidation,/usr/local/lib/python3.8/dist-packages/ihm/:/opt/conda/lib/python3.10/site-packages/ihm/,input:/ihmv/input,cache:/ihmv/cache,output:/ihmv/output ihmv_20231222.sif /opt/IHMValidation/ihm_validation/ihm_validator.py -f /ihmv/input/PDBDEV_00000001.cif --force --output-root /ihmv/output --cache-root /ihmv/cache
```

and here is only  the added part:
```
/usr/local/lib/python3.8/dist-packages/ihm/:/opt/conda/lib/python3.10/site-packages/ihm/
```

There is a minor version mismatch (3.8 vs 3.10) but it still works fine. I've tested it as `pdbihm` on both dev and production instances.

**Comment by brindakv** [comment] 2024-03-20 15:48
@svoinea Please confirm if the above update from @aozalevsky has been implemented on `dev` / `production` workflows. 

I am running tests and would like to know if `python-ihm` from the host machine is being used for generating the validation reports.

**Comment by svoinea** [comment] 2024-03-20 18:20
@aozalevsky I have added the function to checkout the `IHMValidation`.

1. On `production`, the script is `/root/ihm_validation_checkout.sh`. The checkout is for the tag `20240315`:
```
    "python_ihm_validation 20240315"
```
Therefore:
```
git log -1
commit 183844f9c5c6582931eea635ce6f669f3d67992e (HEAD, tag: 20240315)
Author: Arthur Zalevsky <aozalevsky@gmail.com>
Date:   Fri Mar 15 14:18:57 2024 -0700

    improved check for SASBDB ids to support 809152b
```
Each time you want to apply a new tag, set its value in the `/root/ihm_validation_checkout.sh` script and run it.


2. On `dev`, we have the daily script `/etc/cron.daily/dev-update`. The checkout for `IHMValidation` is for the latest `dev_2.0`:
```
    "python_ihm_validation origin/dev_2.0"
```
Therefore:
```
git log -1
commit cf90346a721d86168b1ceeac63f648e8ae264ce6 (HEAD, origin/dev_2.0, dev_2.0)
Author: Arthur Zalevsky <aozalevsky@gmail.com>
Date:   Wed Mar 20 08:08:14 2024 -0700

    added python-ihm version and bumped report version to 1.1
```
Each time you want to apply an update, run manually the script `/etc/cron.daily/dev-update`.
Or if want a specific tag, replace `origin/dev_2.0` by the tag value, and then run the script.

The symbolic link is `NOT` any more necessary, so, I removed it.
It is up to you if you want to remove the directories `IHMValidation_2.0_*`.

The generated log file is `/root/pdb-cron-hourly-update.log`.

**Comment by aozalevsky** [comment] 2024-03-20 18:22
@svoinea got it, thanks for the update and instruction.

**Comment by aozalevsky** [comment] 2024-03-26 18:19
@svoinea here is a backup cron cleanup job for the validation pipeline: 

https://github.com/salilab/IHMValidation/issues/80#issuecomment-2021169176

**Comment by svoinea** [comment] 2024-03-27 01:20
@aozalevsky The command:
```
find /tmp -cmin +60 -type d -maxdepth 1 -regex ".*rust_.*\|.*Temp-.*" -exec rm -r {} \;
```
is removing just directories like `Temp*` and `rust_mozprofile* `.

There are other directories like `config*` and `pymp-*` that are not deleted.

From what I see on the AWS production which executes the PDB service w/o the `singularity`, such directories are not generated.

**Comment by brindakv** [comment] 2024-03-27 01:25
@aozalevsky Please check the validation report generation workflow to identify steps that create these empty directories. Based on @svoinea's observation, these are not created on production, where validation reports are not generated. 

Please provide @svoinea an updated command for the cron job.

**Comment by svoinea** [comment] 2024-03-27 01:26
@aozalevsky The command is generating also the following warning:
```
find: warning: you have specified the global option -maxdepth after the argument -cmin, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
```

**Comment by aozalevsky** [comment] 2024-03-27 02:51
@svoinea `pymp*` are indeed generated by the pipeline (if the `multiprocessing` call wasn't terminated cleanly, they are left in the `/tmp`). As to `config-util*cache`, I'm not sure since, as I mentioned, I don't have it on any of the other machines where I tested the pipeline. Anyway, they look harmless, so we clean them too. here is an updated command (also, without the warning)

`find /tmp -maxdepth 1 -cmin +60 -type d -regex ".*rust_.*\|.*Temp-.*\|.*pymp.*\|.*config-util.*-cache" -exec rm -r {} \;`

**Comment by svoinea** [comment] 2024-03-27 04:57
@brindakv @aozalevsky I have checked on `ubuntu production`and the current `testSchemaDataPrepValidate-ihm.py` script is the one that generates the `/tmp/config-util*-cache` directories.

**Comment by aozalevsky** [comment] 2024-03-27 22:49
@svoinea, Thanks for pointing this out. I'm not familiar with this script, but it looks like it's part of the rcsb package, so I guess @brindakv should know. 

Overall, we've tracked sources of all temp files, which is very good. The command from the previous message should take care of all of them.

**Comment by aozalevsky** [comment] 2024-04-02 18:06
@brindakv can we close this one? Integration is complete for now, and this issue is pretty long as it is.

**Closed** 2024-04-02 18:09 UTC
Labels: Deploy
