### ISSUE TITLE
Hyperlinks to DOIs and Pubmed IDs

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#18] opened 2019-12-03 20:22 UTC
How do we create hyperlinks to publication DOIs and Pubmed IDs?

**Comment by hongsudt** [comment] 2019-12-03 22:33
Can you provide more detail?


Usually, you can do this through a markdown syntax such as [name](url) where name and url can be column values in the db.  If you want to change a particular column to display a hyperlink, this can be set through "column-display" annotation..


________________________________

**Comment by brindakv** [comment] 2019-12-05 20:17
From @hongsudt, use column display annotation. Eg: 

`"*": {"markdown_pattern" : "[{{{doi}}}]{https://doi.org/{{{doi}}}}"}`

**Comment by svoinea** [comment] 2019-12-06 02:29
The problem is fixed now.
This is how the column `pdbx_database_id_DOI` is displayed now in the compact context:
![Screenshot-5](https://user-images.githubusercontent.com/1609577/70290362-7c825d00-178c-11ea-9c25-43bfa5c458cd.png)
When you click on that link, the page at https://doi.org/10.1074/mcp.M114.041673 will be open.
The column annotation was defined in the `citation` table for the column `pdbx_database_id_DOI` as:
```
    'pdbx_database_id_DOI': {
        chaise_tags.column_display: {
            '*': {
                'markdown_pattern': '{{#pdbx_database_id_DOI}}[{{_pdbx_database_id_DOI}}](https://doi.org/{{_pdbx_database_id_DOI}}){{/pdbx_database_id_DOI}}'
            }
        }
    },
```

**Comment by svoinea** [comment] 2020-03-18 01:10
The issue was fixed.

**Closed by svoinea** 2020-03-18 01:10 UTC
